notifications:
  email:
    on_success: never

matrix:
  include:
    - language: python
      python:
        - "nightly"
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
