notifications:
  email:
    on_success: never

matrix:
  include:
    # __CHANGE_ME_CIs_or_REMOVE_thisFile__
    - language: python
      python:
        - "nightly"
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
